### ISSUE TITLE
Some getHierarchiesByLatLon results do not include a continent

### ISSUE THREAD

**Issue by simonw** [whosonfirst/whosonfirst-www-api#50]
Most of the calls I have made to getHierarchiesByLatLon have included the continent - such that my calling code now expects all responses to include a continent key. Then I found this one for 37.749383, -97.587331 which does NOT return a continent key:

https://whosonfirst-api.mapzen.com/?spr=1&longitude=-97.587331&extras=geom%3A&latitude=37.749383&method=whosonfirst.places.getHierarchiesByLatLon&api_key=mapzen-...

Full response I'm seeing from that is:

    {
        "hierarchies": [
            {
                "region": {
                    "wof:id": 85688555,
                    "wof:parent_id": "85633793",
                    "wof:name": "Kansas",
                    "wof:placetype": "region",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data",
                    "geom:longitude": -98.380161,
                    "geom:type": "Polygon",
                    "geom:bbox": "-102.051769,36.993016,-94.588387,40.003166",
                    "geom:latitude": 38.484725,
                    "geom:area": 22.004756
                },
                "locality": {
                    "wof:id": 85945871,
                    "wof:parent_id": "404504929",
                    "wof:name": "Wichita",
                    "wof:placetype": "locality",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data",
                    "geom:longitude": -97.342582,
                    "geom:type": "MultiPolygon",
                    "geom:area": 0.043447,
                    "geom:bbox": "-97.734265,37.489132,-97.152912,37.8402",
                    "geom:latitude": 37.690628,
                    "geom:area_square_m": "425119079.882"
                },
                "country": {
                    "wof:id": 85633793,
                    "wof:parent_id": "102191575",
                    "wof:name": "United States",
                    "wof:placetype": "country",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data",
                    "geom:longitude": -113.2686,
                    "geom:type": "MultiPolygon",
                    "geom:area": 1166.187278,
                    "geom:bbox": "-179.231086,18.86546,179.859681,71.441059",
                    "geom:latitude": 45.964509
                },
                "neighbourhood": {
                    "wof:id": 85872815,
                    "wof:parent_id": "85945871",
                    "wof:name": "West",
                    "wof:placetype": "neighbourhood",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data",
                    "geom:longitude": -97.561614,
                    "geom:type": "Polygon",
                    "geom:area": 0.021461,
                    "geom:bbox": "-97.661838,37.59892,-97.432486,37.764316",
                    "geom:latitude": 37.682942
                },
                "county": {
                    "wof:id": 102084203,
                    "wof:parent_id": "85688555",
                    "wof:name": "Sedgwick",
                    "wof:placetype": "county",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data",
                    "geom:longitude": -97.460969,
                    "geom:type": "Polygon",
                    "geom:area": 0.266964,
                    "geom:bbox": "-97.808358,37.474184,-97.152145,37.912733",
                    "geom:latitude": 37.684762
                }
            }
        ],
        "stat": "ok"
    }

**Comment by thisisaaronland** [comment]
This was a problem with the data itself for WOF ID [85872815](https://whosonfirst.mapzen.com/spelunker/id/85872815/) which has been updated and should be reflected in prod in ~ 15-20 minutes.

**Comment by simonw** [comment]
Thanks for the quick turnaround :)

I found another one: https://whosonfirst-api.mapzen.com/?spr=1&longitude=-122.5674867&extras=geom%3A&latitude=37.8983063&method=whosonfirst.places.getHierarchiesByLatLon&api_key=mapzen-...

This one's more exciting though, because in addition to not listing a continent it ALSO has a neighbourhood which has a parent_id of -1!

    {
        "hierarchies": [
            {
                "region": {
                    "wof:id": 85688637,
                    "wof:parent_id": "85633793",
                    "wof:name": "California",
                    "wof:placetype": "region",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data",
                    "geom:longitude": -119.663837,
                    "geom:latitude": 37.215297,
                    "geom:type": "MultiPolygon",
                    "geom:area": 43.08336,
                    "geom:bbox": "-124.482003,32.528832,-114.131211,42.009517"
                },
                "country": {
                    "wof:id": 85633793,
                    "wof:parent_id": "102191575",
                    "wof:name": "United States",
                    "wof:placetype": "country",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data",
                    "geom:longitude": -113.2686,
                    "geom:type": "MultiPolygon",
                    "geom:area": 1166.187278,
                    "geom:bbox": "-179.231086,18.86546,179.859681,71.441059",
                    "geom:latitude": 45.964509
                },
                "neighbourhood": {
                    "wof:id": 85886421,
                    "wof:parent_id": "-1",
                    "wof:name": "Panoramic",
                    "wof:placetype": "neighbourhood",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data",
                    "geom:longitude": -122.5978,
                    "geom:type": "Polygon",
                    "geom:area": 0.002434,
                    "geom:bbox": "-122.637733,37.862793,-122.557183,37.921587",
                    "geom:latitude": 37.896197
                },
                "county": {
                    "wof:id": 102084353,
                    "wof:parent_id": "85688637",
                    "wof:name": "Marin",
                    "wof:placetype": "county",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data",
                    "geom:longitude": -122.748859,
                    "geom:type": "Polygon",
                    "geom:area": 0.220184,
                    "geom:bbox": "-123.134523,37.814947,-122.347454,38.321227",
                    "geom:latitude": 38.055183
                }
            }
        ],
        "stat": "ok"
    }

Should I be filing these over in https://github.com/whosonfirst-data/whosonfirst-data/issues instead?

More to the point: is my mental model of getHierarchiesByLatLon  in WhosOnFirst correct? I've been assuming that getHierarchiesByLatLon should return a list of hierarchies, but each of those hierarchies should be a true tree - every element in the hierarchy should have a parent_id that corresponds to another element in that hierarchy. Is this the intended contract for the API?

**Comment by thisisaaronland** [comment]
The short version is: Yes.

The longer version ... well, long. The first thing to understand is that `-1` is a valid ID. It signals that the parent ID can not be determined and/or needs to be vetted by a human. The details are here:

https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof.md#parent_id

What's happening here, specifically, is that we can't find any containing parent of the correct placetype ("macrohood", "borough", "locality") for the neighbourhood in question:

https://github.com/whosonfirst/whosonfirst-placetypes/blob/master/placetypes/neighbourhood.json#L5

The reasons why this can happen include: An invalid or inaccurate parent geometry; An invalid or inaccurate reverse-geocoding centroid (consider that the geometric centroid of SF is in the Pacific Ocean because of the Farralon Islands, which is why we have begun adding explicit `reversegeo:` centroids to records and why we have [custom code](https://github.com/whosonfirst/py-mapzen-whosonfirst-utils/blob/master/mapzen/whosonfirst/utils/__init__.py#L35-L58) for determining which lat,lon to use) and so on. 

In this instance we have a rural neighbourhood that is proximate to a national park so the calculus around "locality" starts to get weird. It's further compounded by the source data for the neighbourhood coming from the Zetashapes project which derived polygons from census blocks and while it works great in urban areas is decidely weird outside of urban areas:

https://whosonfirst.mapzen.com/spelunker/id/85886421/

So, in this case finding the parent of the neighbourhood fails:

```
curl -X GET 'https://whosonfirst-api.mapzen.com?method=whosonfirst.places.getByLatLon&api_key=mapzen-xxxxxx&latitude=37.896197&longitude=-122.5978&placetype=locality&format=json'

{
  "places": [],
  "stat": "ok"
}
```

What we try to do in these situations, absent an immediate parent from which we can derive a complete hierarchy, is to ensure that every record has a hierarchy for its nearest ancestor which, in this case, is the county. There is a handy graph of the placetype hierarchies and relationships here:

https://github.com/whosonfirst/whosonfirst-placetypes#here-is-a-pretty-picture

Does that make sense? Would it be useful or more better to ensure that the API response include a key/object for a missing ancestor with the appropriate flags or ... ?

As for where to file things, it's fine to do so here in as much as the questions you're raising are happening in the context of the API and it's useful to see in that light (even if they are "data" questions).

There is also an ongoing project this summer to consolidate a lot of these "first principles" decisions in a single place and make it all a little more approachable and accessible so these kinds of questions/issues are very useful.

**Comment by thisisaaronland** [comment]
Also, just to confirm per the original issue:

```
curl -X GET 'https://whosonfirst-api.mapzen.com?method=whosonfirst.places.getHierarchiesByLatLon&api_key=mapzen-xxxxxx&latitude=37.749383&longitude=-97.587331&format=json'

{
  "hierarchies": [
    {
      "neighbourhood_id": 85872815,
      "continent_id": 102191575,
      "localadmin_id": "404504929",
      "country_id": 85633793,
      "locality_id": 85945871,
      "county_id": 102084203,
      "region_id": 85688555
    }
  ],
  "stat": "ok"
}
```

**Comment by simonw** [comment]
Thanks for the explanation, this is fascinating.

In the case of the neighbourhood of "Panoramic", https://whosonfirst.mapzen.com/spelunker/id/85886421/#12/37.8922/-122.5975 I think my preferred situation would be for it to be a neighbourhood with a county as its parent_id (Marin, 102084353) - but I guess a neighbourhood with a county as a parent is in violation of the intended hierarchy set out in https://github.com/whosonfirst/whosonfirst-placetypes

I'm trying to model the subset of whosonfirst that I care about as a simple hierarchy, so in this particular case I'd have to skip "Panoramic" entirely. I guess I could model it as a child of Marin in my own dataset, but that feels like it would be setting a precedent that would be hard to maintain in the future.
