### ISSUE TITLE
getHierarchiesByLatLon 39.950713,-74.95249 in Buffalo NY returns empty list, should return hierarchy

### ISSUE THREAD

**Issue by simonw** [whosonfirst/whosonfirst-www-api#55]
http://whosonfirst-api.mapzen.com/?method=whosonfirst.places.getHierarchiesByLatLon&latitude=39.950713&longitude=-74.95249&api_key=xxx

Returns the following:

    {
        "hierarchies": [],
        "stat": "ok"
    }

If you hit the same point on the mapzen reverse API you do get results:

https://search.mapzen.com/v1/reverse?point.lat=42.88685&point.lon=-78.87569&sources=wof&layers=coarse&size=1&&api_key=xxx

    {
        "geocoding": ...,
        "type": "FeatureCollection",
        "features": [
            {
                "properties": {
                    "id": "85867085",
                    "gid": "whosonfirst:neighbourhood:85867085",
                    "layer": "neighbourhood",
                    "source": "whosonfirst",
                    "source_id": "85867085",
                    "name": "Downtown",
                    "confidence": 0.6,
                    "distance": 0.467,
                    "accuracy": "centroid",
                    "country": "United States",
                    "country_gid": "whosonfirst:country:85633793",
                    "country_a": "USA",
                    "region": "New York",
                    "region_gid": "whosonfirst:region:85688543",
                    "region_a": "NY",
                    "county": "Erie County",
                    "county_gid": "whosonfirst:county:102082387",
                    "localadmin": "Buffalo",
                    "localadmin_gid": "whosonfirst:localadmin:404522329",
                    "locality": "Buffalo",
                    "locality_gid": "whosonfirst:locality:85978023",
                    "neighbourhood": "Downtown",
                    "neighbourhood_gid": "whosonfirst:neighbourhood:85867085",
                    "label": "Downtown, Buffalo, NY, USA"
                }
            }
        ]
    }

Here's what that point looks like on Google Maps: https://www.google.com/maps/place/42°53'12.7"N+78°52'32.5"W/

**Comment by thisisaaronland** [comment]
Okay, I can see what's going on. There are a series of overlapping issues:

1. The basic point-in-polygon test for finding the parent of Centerton Square (420526673) fails because it has no centroids (reversegeo or otherwise) that intersect with Moorestown-Lenola (85976171):

https://whosonfirst.mapzen.com/spelunker/id/420526673
https://whosonfirst.mapzen.com/spelunker/id/85976171

2. Centerton Square is classified as a neighbourhood which is incorrect as it appears to be shopping center, in Mount Laurel, so it should be deprecated and re-classified either as a venue or a microhood (there is an ongoing discussion about the "nature" of shopping centers... cc @stepps00)

3. The Centerton Square website suggests that it is in Mount Laurel which is a `localadmin` in WOF, although the GOOG seems to think it's in the (WOF) locality of Moorestown which is itself parented by the localadmin of Moorestown (and not Mount Laurel).

3. The API code does not attempt to "ensure" a hierarchy for a record – that is, if a record's parent ID is `-1` or its hierarchy is already empty (because the parent ID is `-1` and no other code has ensured that the hierarchy contains known ancestors) then it just returns what's in the record.

4. If I rebuild the hierarchy (ensuring ancestors) for Centerton Square I still end up with a null parent, because there are none, but the hierarchy is filled in as follows (tl;dr - the localadmin of Mount Laurel):

```
INFO:root:Centerton Square (420526673) has CHANGED parent ID is now -1
DEBUG:root:[{u'continent_id': 102191575,
  u'country_id': 85633793,
  u'county_id': 102087415,
  u'localadmin_id': 404477867,
  u'neighbourhood_id': 420526673,
  u'region_id': 85688607}]
```

I am not super keen to add a bunch of duplicate smarts to the API code (#4) so I think what I will do in the short term is update the hierarchy of the record itself (420526673) and that way the API will stop returning an empty hierarchy.

Beyond that there is the open question of whether Centerton Square needs to be updated on an existential level (again, cc @stepps00) at which point we will determine its actual parent and, if need be, assign that property to the `wof:controlled` array to prevent future-robots from being clever during future updates.

I will leave this ticket open until the first pass is complete.

**Comment by thisisaaronland** [comment]
```
curl -X GET 'https://whosonfirst-api.mapzen.com?method=whosonfirst.places.getHierarchiesByLatLon&api_key=mapzen-xxxxxx&latitude=39.950713&longitude=-74.95249&format=json'

{
  "hierarchies": [
    {
      "neighbourhood_id": 420526673,
      "continent_id": 102191575,
      "localadmin_id": "404477867",
      "country_id": 85633793,
      "county_id": 102087415,
      "region_id": 85688607
    }
  ],
  "stat": "ok"
}
```

**Comment by stepps00** [comment]
Filed https://github.com/whosonfirst-data/whosonfirst-data/issues/850 as a follow-up to fix Centerton Square, NJ
